version: "3.9"
services:
  web:
    build: .
    ports:
      - "8080:8080"
      - "2404:2404"
    environment:
      - APP_HOST=0.0.0.0
      - APP_PORT=8080
    volumes:
      - ./.env:/app/.env:ro
